# Generated by Django 2.1.2 on 2018-11-03 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('scales', models.PositiveSmallIntegerField()),
                ('sourceURL', models.URLField()),
                ('fromPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromPort', to='api.Port')),
                ('toPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toPort', to='api.Port')),
            ],
        ),
    ]
