version: '3'
services:
  web:
    build: ./backend
    volumes:
      - ./backend/code:/code
    container_name: tty-backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./db/db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: tty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/code:/code
    container_name: tty-frontend
    ports:
      - 4200:4200
    working_dir: /code
    command: npm run start-docker

  adminer:
    image: adminer
    restart: always
    container_name: tty-adminer
    ports:
      - 8080:8080

