version: '3'
services:
  web:
    build: ./backend
    volumes:
      - ./backend/code:/code
    container_name: tty-backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: tty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    container_name: tty-adminer
    ports:
      - 8080:8080

